sudo: false
language: node_js
node_js:
  - 8
cache:
  directories:
    - ~/.npm
    - frontend/node_modules
before_install:
  - cd frontend
install:
  - npm install
script:
  - npm test
after_success:
  - npm run test:coverage