sudo: false
language: node_js
node_js:
  - 10
notifications:
  email: false
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - npm install
script:
  - npm test
after_success:
  - npm run test:coverage
  - npm run test:chromatic