// flow-typed signature: 69de2f3ac1b1490a6753b610a38737a4
// flow-typed version: <<STUB>>/eslint-plugin-cypress_v^2.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-cypress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-cypress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'eslint-plugin-cypress/index' {
  declare module.exports: $Exports<'eslint-plugin-cypress'>;
}
declare module 'eslint-plugin-cypress/index.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress'>;
}
