// flow-typed signature: 6baad22d6306466227debf6a3709d921
// flow-typed version: <<STUB>>/jest-emotion_v^9.1.3/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-emotion/lib/index' {
  declare module.exports: any;
}

declare module 'jest-emotion/lib/replace-class-names' {
  declare module.exports: any;
}

declare module 'jest-emotion/src/index' {
  declare module.exports: any;
}

declare module 'jest-emotion/src/replace-class-names' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-emotion/lib/index.js' {
  declare module.exports: $Exports<'jest-emotion/lib/index'>;
}
declare module 'jest-emotion/lib/replace-class-names.js' {
  declare module.exports: $Exports<'jest-emotion/lib/replace-class-names'>;
}
declare module 'jest-emotion/src/index.js' {
  declare module.exports: $Exports<'jest-emotion/src/index'>;
}
declare module 'jest-emotion/src/replace-class-names.js' {
  declare module.exports: $Exports<'jest-emotion/src/replace-class-names'>;
}
